:os.cmd('/bin/rm -f *.beam')
IEx.Helpers.c("srs.ex")

IEx.Helpers.c("paxos.ex")

IEx.Helpers.c("test_harness.ex")
IEx.Helpers.c("srs_test.ex")
IEx.Helpers.c("uuid.ex")

IO.puts('Beggining Local Testing of SRS Module')
IO.puts("============")
IO.puts('Test Simple Local')
IO.puts("============")
SRSTest.test_simple(SRSTest.local_setup())
Process.sleep(50)
IO.puts("============")
IO.puts('Test 5 Bookings')
IO.puts("============")
SRSTest.test_simple_5(SRSTest.local_setup())
Process.sleep(50)
IO.puts("============")
IO.puts('Test that a process can not double book')
IO.puts("============")
SRSTest.test_double_booking(SRSTest.local_setup())
Process.sleep(50)
IO.puts("============")
IO.puts('Test that 2 concurrent ballots result in consensus')
IO.puts("============")
SRSTest.test_2_concurrent(SRSTest.local_setup())
Process.sleep(50)
IO.puts("============")
IO.puts('Test that many concurrent ballots result in consensus')
IO.puts("============")
SRSTest.test_many_concurrent(SRSTest.local_setup())
Process.sleep(50)
IO.puts("============")
IO.puts('Test concurrent ballots, cascading failure of a minority participants')
IO.puts("============")
SRSTest.cascading_minority(SRSTest.local_setup())
Process.sleep(500)
IO.puts("============")
IO.puts('Test concurrent ballots, cascading failure of a minority participants, random delays')
IO.puts("============")
SRSTest.cascading_random_delays(SRSTest.local_setup())
Process.sleep(500)
IO.puts("============")
System.halt()
