IEx.Helpers.c("paxos.ex")

IEx.Helpers.c("srs.ex")

# a = String.to_atom("alice@oscars-MacBook-Pro")
# b = String.to_atom("bob@oscars-MacBook-Pro")
# c = String.to_atom("charlie@oscars-MacBook-Pro")
# IO.puts('Starting Paxos')

# pid1 = SRS.start(a, [a, b, c])
# pid2 = SRS.start(b, [a, b, c])
# pid3 = SRS.start(c, [a, b, c])
pid1 = SRS.start(:p1, [:p1, :p2, :p3, :p4, :p5])
pid2 = SRS.start(:p2, [:p1, :p2, :p3, :p4, :p5])
pid3 = SRS.start(:p3, [:p1, :p2, :p3, :p4, :p5])
pid4 = SRS.start(:p4, [:p1, :p2, :p3, :p4, :p5])
pid5 = SRS.start(:p5, [:p1, :p2, :p3, :p4, :p5])
SRS.reserve(pid1, {:seat1, 'Mr.Brown'})
SRS.reserve(pid2, {:seat2, 'Mr.White'})
SRS.reserve(pid3, {:seat3, 'Mr.Pink'})
SRS.reserve(pid4, {:seat4, 'Mr.Orange'})
SRS.reserve(pid5, {:seat5, 'Mr.Blonde'})
Process.sleep(500)
SRS.gets(pid2)
# SRS.status(pid1, :seat2)
